name: Deploy prebuilt Node.js app to Azure Web App - NODE-REACT-EXPRES2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Zip prebuilt app (excluding unnecessary files)
        run: |
          zip -r release.zip . -x "node_modules/*" "*.git*" "tests/*" "*.md"

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'NODE-REACT-EXPRES2'
          slot-name: 'Production'
          package: release.zip
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CE49EA410BD544A993F7D9F9D67F7986 }}